development:
  adapter: postgresql
  encoding: unicode
  database: educapsule_development
  pool: 5
  username: educapsule
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: educapsule_test
  pool: 5
  username: educapsule
  password: